import { getFrequencySource } from "../utils/tryRequire";
import { Radio, Zap, Waveform, Circle, Activity } from "lucide-react-native";

export const healingFrequencies = [
  {
    id: "417hz",
    title: "Fréquence 417 Hz",
    description: "Aide à éliminer les énergies négatives et favorise le changement.",
    frequency: 417,
    icon: Radio,
    colors: ["#36D1DC", "#5B86E5"],
    audioUrl: getFrequencySource("417hz"),
  },
  {
    id: "852hz",
    title: "Fréquence 852 Hz",
    description: "Renforce l’intuition et la connexion spirituelle.",
    frequency: 852,
    icon: Zap,
    colors: ["#8360C3", "#2EBF91"],
    audioUrl: getFrequencySource("852hz"),
  },
  {
    id: "396-hz-417-hz-639-hz",
    title: "Fréquences 396 / 417 / 639 Hz",
    description: "Élimine la peur, facilite la transformation et favorise les relations harmonieuses.",
    frequency: "396-417-639",
    icon: Waveform,
    colors: ["#F7971E", "#FFD200"],
    audioUrl: getFrequencySource("396-hz-417-hz-639-hz"),
  },
  {
    id: "4-7hz-with-417hz-639hz",
    title: "Fréquences 4-7 Hz avec 417 & 639 Hz",
    description: "Aide à atteindre un état méditatif profond et à guérir émotionnellement.",
    frequency: "4-7-417-639",
    icon: Circle,
    colors: ["#00C9FF", "#92FE9D"],
    audioUrl: getFrequencySource("4-7hz-with-417hz-639hz"),
  },
  {
    id: "8-to-12-hz",
    title: "Fréquence 8 à 12 Hz",
    description: "Favorise la relaxation, la concentration et la créativité.",
    frequency: "8-12",
    icon: Activity,
    colors: ["#43C6AC", "#F8FFAE"],
    audioUrl: getFrequencySource("8-to-12-hz"),
  },
  {
    id: "10hz",
    title: "Fréquence 10 Hz",
    description: "Stimule la relaxation et la mémoire, souvent utilisée pour la méditation.",
    frequency: 10,
    icon: Radio,
    colors: ["#36D1DC", "#5B86E5"],
    audioUrl: getFrequencySource("10hz"),
  },
  {
    id: "33hz",
    title: "Fréquence 33 Hz",
    description: "Équilibre les émotions et renforce la stabilité intérieure.",
    frequency: 33,
    icon: Circle,
    colors: ["#4CA1AF", "#C4E0E5"],
    audioUrl: getFrequencySource("33hz"),
  },
  {
    id: "66hz",
    title: "Fréquence 66 Hz",
    description: "Aide à la régénération physique et au bien-être global.",
    frequency: 66,
    icon: Waveform,
    colors: ["#00B4DB", "#0083B0"],
    audioUrl: getFrequencySource("66hz"),
  },
  {
    id: "1441hz",
    title: "Fréquence 1441 Hz",
    description: "Augmente la clarté mentale et l’alignement énergétique.",
    frequency: 1441,
    icon: Zap,
    colors: ["#283048", "#859398"],
    audioUrl: getFrequencySource("1441hz"),
  },
  {
    id: "2772hz",
    title: "Fréquence 2772 Hz",
    description: "Apaise les tensions et favorise la reconnexion à soi.",
    frequency: 2772,
    icon: Radio,
    colors: ["#FF512F", "#DD2476"],
    audioUrl: getFrequencySource("2772hz"),
  },
];
