import { getFrequencySource, getVideoSource } from '../utils/tryRequire';

export const frequencies = [
  {
    id: "4-7hz-with-417hz-639hz",
    title: "4-7Hz avec 417Hz et 639Hz",
    description: "Relaxation profonde et guérison émotionnelle.",
    frequency: "4-7Hz / 417Hz / 639Hz",
    audio: getFrequencySource("4-7hz-with-417hz-639hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "8-to-12-hz",
    title: "8 à 12Hz",
    description: "Concentration et vigilance accrue.",
    frequency: "8-12Hz",
    audio: getFrequencySource("8-to-12-hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "10hz",
    title: "10Hz",
    description: "Relaxation et méditation légère.",
    frequency: "10Hz",
    audio: getFrequencySource("10hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "33hz",
    title: "33Hz",
    description: "Équilibre du corps et de l’esprit.",
    frequency: "33Hz",
    audio: getFrequencySource("33hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "66hz",
    title: "66Hz",
    description: "Nettoyage énergétique et recentrage intérieur.",
    frequency: "66Hz",
    audio: getFrequencySource("66hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "396-hz-417-hz-639-hz",
    title: "396Hz / 417Hz / 639Hz",
    description: "Guérison des émotions et ouverture du cœur.",
    frequency: "396Hz / 417Hz / 639Hz",
    audio: getFrequencySource("396-hz-417-hz-639-hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "417hz",
    title: "417Hz",
    description: "Libération des émotions négatives.",
    frequency: "417Hz",
    audio: getFrequencySource("417hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "852hz",
    title: "852Hz",
    description: "Activation de l’intuition et élévation spirituelle.",
    frequency: "852Hz",
    audio: getFrequencySource("852hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "1441hz",
    title: "1441Hz",
    description: "Éveil et clarté mentale.",
    frequency: "1441Hz",
    audio: getFrequencySource("1441hz"),
    video: getVideoSource("frequence"),
  },
  {
    id: "2772hz",
    title: "2772Hz",
    description: "Harmonisation complète des centres énergétiques.",
    frequency: "2772Hz",
    audio: getFrequencySource("2772hz"),
    video: getVideoSource("frequence"),
  },
];
