import { getAudioSource, getVideoSource } from '../utils/tryRequire';
import {
  CloudRain,
  Flame,
  Trees,
  Waves,
  Wind,
  CloudLightning,
  Radio,
  Droplets,
} from 'lucide-react-native';

export const sleepSounds = [
  {
    id: 'pluie-douce',
    title: 'Pluie douce',
    description: 'Le son apaisant d’une pluie légère tombant doucement.',
    icon: CloudRain,
    colors: ['#4facfe', '#00f2fe'],
    audioUrl: getAudioSource('pluie-douce'),
    videoUrl: getVideoSource('pluie-douce'),
  },
  {
    id: 'feu-de-camp',
    title: 'Feu de camp',
    description: 'Le crépitement réconfortant du feu de bois.',
    icon: Flame,
    colors: ['#f7971e', '#ffd200'],
    audioUrl: getAudioSource('feu-de-camp'),
    videoUrl: getVideoSource('feu-de-camp'),
  },
  {
    id: 'foret-paisible',
    title: 'Forêt paisible',
    description: 'Les bruits d’oiseaux et le vent dans les arbres.',
    icon: Trees,
    colors: ['#11998e', '#38ef7d'],
    audioUrl: getAudioSource('foret-paisible'),
    videoUrl: getVideoSource('foret-paisible'),
  },
  {
    id: 'vague-de-locean',
    title: 'Vagues de l’océan',
    description: 'Le roulis régulier des vagues sur la plage.',
    icon: Waves,
    colors: ['#2193b0', '#6dd5ed'],
    audioUrl: getAudioSource('vague-de-locean'),
    videoUrl: getVideoSource('vague-de-locean'),
  },
  {
    id: 'vent-leger',
    title: 'Vent léger',
    description: 'Une brise douce et apaisante.',
    icon: Wind,
    colors: ['#83a4d4', '#b6fbff'],
    audioUrl: getAudioSource('vent-leger'),
    videoUrl: getVideoSource('vent-leger'),
  },
  {
    id: 'riviere-calme',
    title: 'Rivière calme',
    description: 'Le murmure tranquille d’un cours d’eau.',
    icon: Droplets,
    colors: ['#36d1dc', '#5b86e5'],
    audioUrl: getAudioSource('riviere-calme'),
    videoUrl: getVideoSource('riviere-calme'),
  },
  {
    id: 'orage-apaisant',
    title: 'Orage apaisant',
    description: 'Le grondement lointain du tonnerre accompagné de la pluie.',
    icon: CloudLightning,
    colors: ['#232526', '#414345'],
    audioUrl: getAudioSource('orage-apaisant'),
    videoUrl: getVideoSource('orage-apaisant'),
  },
  {
    id: 'bruit-blanc',
    title: 'Bruit blanc',
    description: 'Un son constant qui aide à se concentrer ou à s’endormir.',
    icon: Radio,
    colors: ['#283048', '#859398'],
    audioUrl: getAudioSource('bruit-blanc'),
    videoUrl: getVideoSource('bruit-blanc'),
  },
];
